#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# Set up workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Set cursor
xsetroot -cursor_name left_ptr &

# Configure bspwm settings
bspc config normal_border_color "F#F0C674"
bspc config focused_border_color "F#F0C674" # Example color, replace with appropriate color

bspc config border_width 1
bspc config window_gap 10
bspc config top_padding 6
bspc config split_ratio 0.5

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

feh  --bg-scale --randomize ~/.wall
polybar&

